update a lot of stuff

diff --git a/.local/bin/visual b/.local/bin/visual
--- a/.local/bin/visual
+++ b/.local/bin/visual
@@ -1,3 +1,8 @@
 #!/usr/bin/env sh
 
-emacsclient -c -a "" $@
+# shellcheck disable=SC2015
+systemctl --user start emacs.service &&
+	emacsclient -c "$@" || (
+	notify-send "Failed to start Emacs"
+	echo "Failed to start Emacs"
+)
